steps:
# running docker-compose
#STEP 00
- id: 'Step 00 - Realizando docker-compose up'
  name: 'gcr.io/$PROJECT_ID/docker-compose:1.24.0'
  args: ['-f', './laravel/docker-compose.cloudbuild.yaml', 'up', '-d']
  
#STEP 01
- id: 'Step 01 - Rodando docker ps'
  name: 'gcr.io/cloud-builders/docker'
  args: ['ps']

#STEP 02
- id: 'Step 02 - Rodando composer install'
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-d', 'app', 'composer', 'install']

#STEP 04
- id: 'Step 04 - Copiando .env'
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-d', 'app', 'cp', '.env.example', '.env']

#STEP 05
- id: 'Step 05 - Key generate'
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-d', 'app', 'php', '/var/www/artisan', 'key:generate']

#STEP 06
- id: 'Step 06 - Executar'
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-d', 'app', 'php-fpm']